### PR TITLE
fix: use gzip compression only for /write endpoint

### LINKED ISSUE #848: Queries throw a "missing required parameter "q"" exception using influxdb-java 2.22 with enableGzip set to true
Queries throw an exception about missing required parameter q when using the latest influxdb-java 2.22 with the enableGzip set to true. I am using influxdb-java 2.22, influxdb-server 1.8.10 on CentOS 7.

Here's my connection setup code

```
    OkHttpClient.Builder builder = new OkHttpClient.Builder().readTimeout(readTimeout, TimeUnit.SECONDS).writeTimeout(writeTimeout, TimeUnit.SECONDS);
    InfluxDB influxDB = InfluxDBFactory.connect(databaseUrl, databaseUser, databasePassword, builder, ResponseFormat.MSGPACK);
    influxDB.enableGzip();
```

This is the exception that gets thrown. My process's first query to influxdb is to create the database which this stack is for.

```
org.influxdb.InfluxDBException: missing required parameter "q"
        at org.influxdb.InfluxDBException.buildExceptionFromErrorMessage(InfluxDBException.java:161) ~[influxdb-java-2.22.jar:?]
        at org.influxdb.InfluxDBException.buildExceptionForErrorState(InfluxDBException.java:189) ~[influxdb-java-2.22.jar:?]
        at org.influxdb.impl.InfluxDBImpl.execute(InfluxDBImpl.java:844) ~[influxdb-java-2.22.jar:?]
        at org.influxdb.impl.InfluxDBImpl.executeQuery(InfluxDBImpl.java:833) ~[influxdb-java-2.22.jar:?]
        at org.influxdb.impl.InfluxDBImpl.createDatabase(InfluxDBImpl.java:743) ~[influxdb-java-2.22.jar:?]
```

If I leave enableGzip set to false, everything works.

### PR DESCRIPTION
**Pull request by bednar**
Closes #848

## Proposed Changes

Only the request to `/write` endpoint should be compressed by GZIP.

- https://github.com/influxdata/influxdb/blob/d01ea614650b8682e9f3097115333c380981ad93/services/httpd/handler.go#L1588
- https://github.com/influxdata/influxdb/blob/d01ea614650b8682e9f3097115333c380981ad93/services/httpd/handler.go#L571

## Checklist

- [x] CHANGELOG.md updated
- [x] Rebased/mergeable
- [x] `mvn test` completes successfully
- [x] Commit messages are [conventional](https://www.conventionalcommits.org/en/v1.0.0/)
- [x] Sign [CLA](https://www.influxdata.com/legal/cla/) (if not already signed)

### CODE REVIEW

File: src/test/java/org/influxdb/InfluxDBTest.java [hunk 1]
```diff
@@ -1457,6 +1457,13 @@ public String call() throws Exception {
     Assertions.assertTrue(MyInfluxDBBean.OKHTTP_BUILDER.interceptors().isEmpty());
   }
 
+  @Test
+  public void testQueryPostWithGZIPCompression() {
+    this.influxDB.enableGzip();
+    String command = String.format("CREATE DATABASE db_gzip_%d", System.currentTimeMillis());
+    this.influxDB.query(new Query(command, null, true));
```
Comment (majst01) [inline src/test/java/org/influxdb/InfluxDBTest.java:1464]: shouldn't we test the result meets some expectations ?

**Review by majst01 — CHANGES_REQUESTED** [review]

File: src/test/java/org/influxdb/InfluxDBTest.java (hunk 1 above)
Comment (bednar) [reply src/test/java/org/influxdb/InfluxDBTest.java]: I've added a test to check the result of `CREATE DATABASE ...`.

**Review by majst01 — APPROVED** [review]

**Comment by majst01** [comment]
@bednar thanks for taking care, can you create a release out of current master ?

**Comment by bednar** [comment]
@majst01, I am out of office tomorrow. I will release the client at Thursday.

**Comment by majst01** [comment]
> @majst01, I am out of office tomorrow. I will release the client at Thursday.

OK
